baseURL: "https://lindajzmin-website.netlify.app"
languageCode: "es"
title: "Linda Cabrera"
theme: hugo-profile

Paginate: 3
disqusShortname: lindajzmin
googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: about
      name: Resumen
      title: About
      url: /resumen
      weight: 1
      
    - identifier: education
      name: Educación
      title: Education
      url: /educacion
      weight: 2

    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 3
      
    # - identifier: gallery
    #  name: Galeria
    #  title: Blog posts
    #  url: /gallery
    #  weight: 4
    
    - identifier: courses
      name: Cursos
      title: Blog posts
      url: /cursos
      weight: 5

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Linda Cabrera Orellana"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/hex-l.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  color:
  #   textColor:
  #   secondaryTextColor:
    backgroundColor: "white"
  #  secondaryBackgroundColor: "linen"
    primaryColor: "purple"
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor: "navy"
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
     align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
     brandLogo: "/hex-l.png" # Logo for the brand | default is the favicon variable
     brandName: "lindateachtech" # Brand name for the brand | default is the title variable

     menus:
       disableAbout: true
       disableExperience: true
       disableEducation: true
       disableProjects: true
       disableAchievements: true
       disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hola, mi nombre es"
    title: "Linda."
    content: "Soy una profesional con experiencia en análisis de datos, modelado predictivo, visualización avanzada de datos y la enseñanza en el manejo de softwares. Especializada en programación en R, Python, y herramientas como SQL, Power BI y Looker, aplico algoritmos de machine learning para generar estrategias que optimicen procesos y el flujo empresarial. Apasionada por transformar datos en soluciones innovadoras, tengo un fuerte interés en roles relacionados con ciencia de datos, investigación y mejora continua en entornos dinámicos y tecnológicos. Desde hace 4 años, estoy profundamente comprometida con la comunidad de R y su desarrollo, aportando desde R‑Ladies y en la organización de varios eventos relacionados."
    image: /images/ljco3.png
    button:
      enable: true
      name: "Curriculum Vitae"
      url: "https://github.com/lindateachtech/mi-cv/blob/main/CV.pdf"
      download: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/lindateachtech
        - icon: fab fa-twitter
          url: https://twitter.com/lindateachtech
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/lindateachtech/

  # About
  # about:
  #    enable: true
  #    title: "Sobre mi"
  #    image: "/images/lindacv2.jpg"
  #    content: |-
  #    Soy especialista en técnicas cuantitativas para la gestión empresarial, con amplia experiencia en la implementación de mejoras en procesos empresariales y análisis de datos.
      
  #    Tengo una sólida formación académica en Auditoría, con un enfoque en procesos, poseo un Máster en Investigación Matemática y otro en Técnicas Cuantitativas para la Gestión Empresarial. 
      
  #    Durante mi trayectoria profesional, trabajé como Especialista de Planificación y Gestión de Procesos donde me enfoqué en la aplicación de herramientas de análisis de datos para la toma de decisiones basadas en datos, incluyendo la implementación de la norma ISO 9001:2008 y luego como Directora Administrativa, liderando equipos, coordiné diversas áreas como talento humano, compras, inventario, seguros y servicios generales, donde desarrollé procesos eficientes como por ejemplo para la toma física de inventario y su control, lo que permitió a la empresa generar ahorros significativos.
      
  #    Además, tuve la oportunidad de desempeñarme como profesora universitaria en áreas como cálculo, ecuaciones diferenciales y estadística. Esta experiencia me permitió desarrollar habilidades en la enseñanza efectiva de conceptos complejos, y he logrado transmitir mi pasión por el aprendizaje a mis estudiantes. Además de la enseñanza, también me dediqué a promover la participación de los estudiantes en actividades complementarias, las cuales los ayudaron a ampliar sus horizontes y a enriquecer su experiencia universitaria. 
      
  #    En mi rol más reciente como Data Analyst, me he dedicado a la creación de dashboards interactivos con herramientas como Looker, Looker Studio y Power BI. He liderado proyectos de análisis de datos avanzados, como el desarrollo de un modelo de Marketing Mix Modeling, la segmentación de datos mediante clústeres y la implementación de análisis de textos con técnicas de procesamiento de lenguaje natural (NLP). Mi trabajo se ha enfocado en áreas clave como marketing digital, optimización de procesos empresariales y medición de resultados, siempre asegurando la precisión y calidad de los datos.
      
  #    Desde 2021 soy co-organizadora de R-Ladies Guayaquil, un pasatiempo maravilloso que me ha ayudado a expandir mis habilidades en programación y análisis de datos. Como miembro activo de la comunidad de R he contribuido en la planificación y ejecución de talleres en las áreas de estadística, visualización de datos y ciencia de datos con R. Estos talleres son una oportunidad para que los miembros de la comunidad aprendan nuevas habilidades y compartan conocimientos.

  #    Además de mi experiencia profesional y mi trabajo voluntario, soy Instructora de Software Carpentry por lo que he brindado cursos de R para análisis de datos y para investigación científica, donde he tenido la oportunidad de conocer y enseñar a personas de diferentes niveles y contextos a mejorar sus habilidad técnológicas. Soy una apasionada por el lenguaje de programación R y tengo un interés particular en la visualización de datos.
      
  #    Soy una apasionada por la aplicación de técnicas cuantitativas en la gestión empresarial, con un alto grado de compromiso en seguir aprendiendo y compartiendo mis conocimientos con la comunidad empresarial y educativa. 
      
  #  skills:
  #    enable: true
  #    title: "Algunas de las tecnologías y programas en los que he trabajado:"
  #    items:
  #      - "R, Python, SQL"
  #      - "LaTeX, Markdown"
  #      - "Power Bi, Looker, Looker Studio"
  #      - "Git, Shiny, BigQuery"
  #      - "Excel"



  # Experience
  # experience:
    #enable: true
    #title: "Experiencia"
    #items:
    #  - job: "Software Instructor"
    #    company: "Sociedad Ecuatoriana de Estadística"
    #    companyUrl: "https://example.com"
    #    date: "Apr 2022 - present"
    #    featuredLink:
    #      enable: true
    #      name: "View the project"
    #      url: "https://github.com/lindajzmin/course-r-research"
    #    content: "I am currently working as a software instructor at [Sociedad Ecuatoriana de Estadística](https://see-ec.org/wordpress/programas/). I am currently teaching data manipulation, visualization and communication with R."

    #  - job: "Co-Organizer"
    #    company: "R-Ladies Guayaquil"
    #    companyUrl: "https://example.com"
    #    date: "Apr 2021 - present"
    #    featuredLink:
    #      enable: true
    #      url: "https://twitter.com/RLadiesGye"
    #    info:
    #      enable: true
    #      content: Working as Co-Organizer at R-Ladies Guayaquil for more than one year.
    #    content: |
    #      Support minority gender R enthusiasts to achieve their programming potential, through:
    #      - Organize workshops on the use of R in different areas.
    #      - Manage social networks for the diffusion of activities (Twitter, Facebook and Meetup).
    #      - Generate content on social networks to facilitate the individual and collective progress of R enthusiasts

    #  - job: "Professor"
    #    company: "UTMACH"
    #    companyUrl: "https://www.utmachala.edu.ec/portalwp/"
    #    date: "May 2019 - Sep 2022"
    #    info:
    #      enable: true
    #      content: Worked as Professor for more than three years.
    #    featuredLink:
    #      enable: true
    #      name: "Activities"
    #      url: "https://www.facebook.com/alimentosutmach"
    #    content: |
    #      Full-time university professor of Statistics, Calculus and Differential Equations.
    #      Other activities:
    #      - Member of the Quality Management and Accreditation Committee. 
    #      - Management of indicators and analysis of education data with R.
    #      - Community Manager of the Food Engineering Career.
    #      - Organize complementary academic, sports, cultural and political activities with students.

    #  - job: "Quality Management Assistant"
    #    company: "CELEC EP"
    #    companyUrl: "https://www.celec.gob.ec/celecsur/"
    #    date: "Apr 2013 - Feb 2017"
    #    info:
    #      enable: true
    #      content: Worked as Quality Management Assistant for more than four years.
    #    content: |
    #      Responsible for the quality management system:
    #      - Management and control of company indicators.
    #      - Data analysis with Excel and Bizagi.
    #      - Cost reduction ($140,000) in inventory optimization and process standardization.
    #      - Strategic planning.


  # Education
  # education:
  #  enable: true
  #  title: "Educación"
    # index: true
  #  items:
  #    - title: "Máster en Técnicas Cuantitativas para la gestión empresarial"
  #      school:
  #        name: "Universidad de Granada, España"
  #        url: "https://masteres.ugr.es/tecnicas-cuantitativas-empresas/"
  #      date: "2024"
  #      content: |-
  #        Técnicas econométricas, Herramientas cuantitativas para el análisis de datos económicos y/o empresariales,
  #        Técnicas Cuantitativas para variables empresariales multidimensionales,
  #        Técnicas Cuantitativas para la calidad de la Producción Empresarial,
  #        Gestión de la cadena de suministro.
          
  #        TFM:
  #        Análisis econométrico de las variables que influyen en los salarios de los futbolistas profesionales de las ligas francesa e inglesa.
  #    - title: "Máster en Investigación Matemática"
  #      school:
  #        name: "Universitat Politècnica de València, España"
  #        url: "http://www.upv.es/titulaciones/MUIMA/indexc.html"
  #      date: "2018"
  #      content: |-
  #        Herramientas metodológicas en la investigación matemática, Modelamiento matemático en la industria, Matemática aplicada, Ecuaciones diferenciales aleatorias, Optimización.
          
  #        TFM:
  #        - Algoritmos matemáticos para la detección de tendencias en señales financieras.
  #      featuredLink:
  #        enable: true
  #        name: "TFM"
  #        url: "https://riunet.upv.es/handle/10251/111119"
  #    - title: "Ingeniería en Auditoría"
  #      school:
  #        name: "Escuela Superior Politécnica del Litoral, Ecuador"
  #        url: "https://www.espol.edu.ec/"
  #      date: "2014"
  #      content: |-
  #        Métodos cuantitativos, Matemáticas financieras, Estadística inferencial, Muestreo y diseño de cuestionarios, Administración financiera, Base de datos para auditores, Análisis multivariado y muestreo, Ingeniería de calidad, Auditoría operacional, Auditoría de sistemas informáticos, entre otras 34 asignaturas más.
          
  #        Tesis:
  #        - Diseño de un sistema de gestión por procesos, aplicado a una empresa dedicada a la rectificación de motores.
  #      featuredLink:
  #        enable: true
  #        name: "Tesis"
  #        url: "https://www.dspace.espol.edu.ec/handle/123456789/39500"

  # Achievements
  # achievements:
    # enable: true
    # title: "Custom Name"
    # items:
      #- title: Google kickstart runner
      #  content: I solved all problems with optimal solution.
      #  url: https://example.com
      #- title: Facebook Hackathon Winner
      #  content: Developed a product using Artificial Intelligence.
      #- title: Hugo Profile
      #  content: Developed a theme and getting 1K+ downloads per month.
      #  url: "https://github.com/gurusabarish/hugo-profile"
      #- title: Microsoft Imagine Runner
      #  content: We are developed a product which can help others.
      #- title: Google Summer of Code
      #  content: Contributed to a open source project.
      #  url: https://example.com

  # projects
  projects:
    enable: true
    title: "Proyectos"
    items:
      - title: Minería de texto
        content: Minería de datos de la red social Twitter, análisis de textos, análisis de sentimientos y LDA sobre Pablo Hasel.
        image: /images/projects/textmining.png
        #featured:
        #  name: Demo
        #  link: https://hugo-profile.netlify.app
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
        #  - icon: fa fa-envelope
        #    url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/lindateachtech/text_mining
        #  - icon: fab fa-twitter
        #    url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile
          - icon: fas fa-link
            url: https://lindaj-cabrera.medium.com/el-debate-en-twitter-sobre-el-encarcelamiento-de-pablo-has%C3%A9l-en-el-segundo-d%C3%ADa-de-manifestaciones-77cf5ddf5273
      - title: SIMTEXT
        content: Una aplicación en Shiny que compara grandes listados de texto utilizando el cálculo de similitud del coseno.
        image: /images/projects/simtext2.jpg
        featured:
          name: App
          link: https://linda-cabrera.shinyapps.io/simtext/
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
        #  - icon: fa fa-envelope
        #    url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
        #  - icon: fab fa-github
        #    url: https://github.com/lindateachtech/text_mining
        #  - icon: fab fa-twitter
        #    url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile
          - icon: fas fa-link
            url: https://lindajzmin-website.netlify.app/blogs/simtext/


  #Contact
  contact:
    enable: true
    title: "Contacto"
    content: Mi bandeja de entrada siempre está abierta. Ya sea que tenga una pregunta o simplemente quiera saludar, ¡haré todo lo posible para responderle!
    email: lindateachtech@gmail.com
    btnName: Escríbeme

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/lindateachtech
      twitter: https://twitter.com/lindateachtech
      linkedin: https://www.linkedin.com/in/lindateachtech/